version: '3.0'
services:
  client:
    container_name: xuumin-client
    build:
      context: .
      dockerfile: ./xuumin-client/Dockerfile
    environment:
      - PORT=4000
    ports:
      - 4000:4000
    volumes:
      - ./xuumin-client:/app:cached
    depends_on: [server-gateway]

  server:
    container_name: xuumin-server
    build:
      context: .
      dockerfile: ./xuumin-server/Dockerfile
    environment:
      - PORT=5000
      - DATABASE_URI=postgres://pguser:pgpassword@xuumin-postgres/pqgotest?sslmode=disable
    ports:
      - 5000:5000
    volumes:
      - go:/go
      - ./:/go/src/github.com/yuya-takeyama/xuumin:cached
    depends_on: [postgres]

  server-gateway:
    container_name: xuumin-server-gateway
    build:
      context: .
      dockerfile: ./xuumin-server-gateway/Dockerfile
    environment:
      - 'GRPC_ENDPOINT=xuumin-server:5000'
    ports:
      - 6000:6000
    volumes:
      - go:/go
      - ./:/go/src/github.com/yuya-takeyama/xuumin:cached

    depends_on: [server]

  postgres:
    container_name: xuumin-postgres
    image: postgres:10.3-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data

  scripts:
    container_name: xuumin-scripts
    build:
      context: .
      dockerfile: ./xuumin-scripts/Dockerfile
    volumes:
      - go:/go
      - ./:/go/src/github.com/yuya-takeyama/xuumin:cached

volumes:
  go:
  postgres-data:
