version: '3.0'
services:
  yaichi:
    container_name: yaichi
    image: mtsmfm/yaichi
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  reverse-proxy:
    container_name: reverse-proxy
    build:
      context: .
      dockerfile: ./reverse-proxy/Dockerfile
    ports:
      - 3000:80
    depends_on: [client, server-gateway, image-service]

  client:
    container_name: client
    build:
      context: .
      dockerfile: ./xuumin-client/Dockerfile
    environment:
      - PORT=4000
    ports:
      - 4000:4000
    volumes:
      - client-node-modules:/app/node_modules
      - ./xuumin-client/config:/app/config:cached
      - ./xuumin-client/public:/app/public:cached
      - ./xuumin-client/scripts:/app/scripts:cached
      - ./xuumin-client/src:/app/src:cached
      - ./xuumin-client/package.json:/app/package.json:cached
      - ./xuumin-client/yarn.lock:/app/yarn.lock:cached
    depends_on: [server-gateway]

  image-service:
    container_name: image-service
    build:
      context: .
      dockerfile: ./xuumin-image-service/Dockerfile
    environment:
    environment:
      - PORT=8000
      - GRPC_ENDPOINT=server:5000
      - PLANTUML_SERVICE_ENDPOINT=http://plantuml-service:3000
    ports:
      - 8000:8000

  server:
    container_name: server
    build:
      context: .
      dockerfile: ./xuumin-server/Dockerfile
    environment:
      - PORT=5000
      - DATABASE_URI=postgres://pguser:pgpassword@postgres/pqgotest?sslmode=disable
    ports:
      - 5000:5000
    volumes:
      - go:/go
      - ./:/go/src/github.com/yuya-takeyama/xuumin:cached
    depends_on: [postgres]

  server-gateway:
    container_name: server-gateway
    build:
      context: .
      dockerfile: ./xuumin-server-gateway/Dockerfile
    environment:
      - 'GRPC_ENDPOINT=server:5000'
    ports:
      - 6000:6000
    volumes:
      - go:/go
      - ./:/go/src/github.com/yuya-takeyama/xuumin:cached
    depends_on: [server, plantuml-service]

  plantuml-service:
    container_name: plantuml-service
    image: yuyat/plantuml-service:latest
    ports:
      - 7000:3000

  postgres:
    container_name: postgres
    image: postgres:10.3-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data

  scripts:
    container_name: scripts
    build:
      context: .
      dockerfile: ./xuumin-scripts/Dockerfile
    volumes:
      - go:/go
      - ./:/go/src/github.com/yuya-takeyama/xuumin:cached

volumes:
  go:
  postgres-data:
  client-node-modules:
